[pytest]
testpaths = tests
python_files = tests_*.py
python_classes = Test*
python_functions = test_*


addopts = -s -v --alluredir=reports/allure-results --video retain-on-failure --output=reports/playwright-output

markers =
    smoke: 冒烟测试
    regression: 回归测试
    P0: 线上定时执行测试