env: test
test:
    base_url: "http://mall.lemonban.com/admin/#/login"
    username: "test123"
    password: "123456"
    validate_code: "lemon"

prod:
    base_url: "https://tool.liumingye.cn/"
    username: "test123"
    password: "123456"

browser:
    type: "chromium"
    headless: true
    slow_mo: 0



context:
  viewport:
    width: 1920
    height: 1080
  ignore_https_errors: true

report:
    screenshot_dir:  "reports/screenshots"
    trace_dir: "reports/traces"
    video_dir: "reports/videos"
    allure_results_dir: "reports/allure-results"

timeout:
    default: 10000
    action: 10000
    navigation: 30000
    expect: 10000
    slow: 30000
